name: Validate and Build the Extension
on:
  push

  workflow_run:
    workflows: ["Create tag"]
    types:
      - completed

jobs:
  validate_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and Build
        uses: typemytype/roboFont-Extension-action@v0.1.0
